//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: google/cloud/location/locations.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate Google_Cloud_Location_LocationsClient, then call methods of this protocol to make API calls.
public protocol Google_Cloud_Location_LocationsClientProtocol: GRPCClient {
  func listLocations(
    _ request: Google_Cloud_Location_ListLocationsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Location_ListLocationsRequest, Google_Cloud_Location_ListLocationsResponse>

  func getLocation(
    _ request: Google_Cloud_Location_GetLocationRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Location_GetLocationRequest, Google_Cloud_Location_Location>

}

extension Google_Cloud_Location_LocationsClientProtocol {

  /// Lists information about the supported locations for this service.
  ///
  /// - Parameters:
  ///   - request: Request to send to ListLocations.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listLocations(
    _ request: Google_Cloud_Location_ListLocationsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Location_ListLocationsRequest, Google_Cloud_Location_ListLocationsResponse> {
    return self.makeUnaryCall(
      path: "/google.cloud.location.Locations/ListLocations",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Gets information about a location.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetLocation.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getLocation(
    _ request: Google_Cloud_Location_GetLocationRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Location_GetLocationRequest, Google_Cloud_Location_Location> {
    return self.makeUnaryCall(
      path: "/google.cloud.location.Locations/GetLocation",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

public final class Google_Cloud_Location_LocationsClient: Google_Cloud_Location_LocationsClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the google.cloud.location.Locations service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Google_Cloud_Location_LocationsProvider: CallHandlerProvider {
  /// Lists information about the supported locations for this service.
  func listLocations(request: Google_Cloud_Location_ListLocationsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Location_ListLocationsResponse>
  /// Gets information about a location.
  func getLocation(request: Google_Cloud_Location_GetLocationRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Location_Location>
}

extension Google_Cloud_Location_LocationsProvider {
  public var serviceName: Substring { return "google.cloud.location.Locations" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: Substring, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "ListLocations":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.listLocations(request: request, context: context)
        }
      }

    case "GetLocation":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.getLocation(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

