//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: google/cloud/websecurityscanner/v1alpha/web_security_scanner.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate Google_Cloud_Websecurityscanner_V1alpha_WebSecurityScannerClient, then call methods of this protocol to make API calls.
public protocol Google_Cloud_Websecurityscanner_V1alpha_WebSecurityScannerClientProtocol: GRPCClient {
  func createScanConfig(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_CreateScanConfigRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_CreateScanConfigRequest, Google_Cloud_Websecurityscanner_V1alpha_ScanConfig>

  func deleteScanConfig(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_DeleteScanConfigRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_DeleteScanConfigRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func getScanConfig(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_GetScanConfigRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_GetScanConfigRequest, Google_Cloud_Websecurityscanner_V1alpha_ScanConfig>

  func listScanConfigs(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_ListScanConfigsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_ListScanConfigsRequest, Google_Cloud_Websecurityscanner_V1alpha_ListScanConfigsResponse>

  func updateScanConfig(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_UpdateScanConfigRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_UpdateScanConfigRequest, Google_Cloud_Websecurityscanner_V1alpha_ScanConfig>

  func startScanRun(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_StartScanRunRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_StartScanRunRequest, Google_Cloud_Websecurityscanner_V1alpha_ScanRun>

  func getScanRun(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_GetScanRunRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_GetScanRunRequest, Google_Cloud_Websecurityscanner_V1alpha_ScanRun>

  func listScanRuns(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_ListScanRunsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_ListScanRunsRequest, Google_Cloud_Websecurityscanner_V1alpha_ListScanRunsResponse>

  func stopScanRun(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_StopScanRunRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_StopScanRunRequest, Google_Cloud_Websecurityscanner_V1alpha_ScanRun>

  func listCrawledUrls(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_ListCrawledUrlsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_ListCrawledUrlsRequest, Google_Cloud_Websecurityscanner_V1alpha_ListCrawledUrlsResponse>

  func getFinding(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_GetFindingRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_GetFindingRequest, Google_Cloud_Websecurityscanner_V1alpha_Finding>

  func listFindings(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_ListFindingsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_ListFindingsRequest, Google_Cloud_Websecurityscanner_V1alpha_ListFindingsResponse>

  func listFindingTypeStats(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_ListFindingTypeStatsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_ListFindingTypeStatsRequest, Google_Cloud_Websecurityscanner_V1alpha_ListFindingTypeStatsResponse>

}

extension Google_Cloud_Websecurityscanner_V1alpha_WebSecurityScannerClientProtocol {

  /// Creates a new ScanConfig.
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateScanConfig.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func createScanConfig(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_CreateScanConfigRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_CreateScanConfigRequest, Google_Cloud_Websecurityscanner_V1alpha_ScanConfig> {
    return self.makeUnaryCall(
      path: "/google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/CreateScanConfig",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Deletes an existing ScanConfig and its child resources.
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteScanConfig.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func deleteScanConfig(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_DeleteScanConfigRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_DeleteScanConfigRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: "/google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/DeleteScanConfig",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Gets a ScanConfig.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetScanConfig.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getScanConfig(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_GetScanConfigRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_GetScanConfigRequest, Google_Cloud_Websecurityscanner_V1alpha_ScanConfig> {
    return self.makeUnaryCall(
      path: "/google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/GetScanConfig",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Lists ScanConfigs under a given project.
  ///
  /// - Parameters:
  ///   - request: Request to send to ListScanConfigs.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listScanConfigs(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_ListScanConfigsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_ListScanConfigsRequest, Google_Cloud_Websecurityscanner_V1alpha_ListScanConfigsResponse> {
    return self.makeUnaryCall(
      path: "/google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListScanConfigs",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Updates a ScanConfig. This method support partial update of a ScanConfig.
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateScanConfig.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func updateScanConfig(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_UpdateScanConfigRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_UpdateScanConfigRequest, Google_Cloud_Websecurityscanner_V1alpha_ScanConfig> {
    return self.makeUnaryCall(
      path: "/google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/UpdateScanConfig",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Start a ScanRun according to the given ScanConfig.
  ///
  /// - Parameters:
  ///   - request: Request to send to StartScanRun.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func startScanRun(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_StartScanRunRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_StartScanRunRequest, Google_Cloud_Websecurityscanner_V1alpha_ScanRun> {
    return self.makeUnaryCall(
      path: "/google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/StartScanRun",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Gets a ScanRun.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetScanRun.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getScanRun(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_GetScanRunRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_GetScanRunRequest, Google_Cloud_Websecurityscanner_V1alpha_ScanRun> {
    return self.makeUnaryCall(
      path: "/google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/GetScanRun",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Lists ScanRuns under a given ScanConfig, in descending order of ScanRun
  /// stop time.
  ///
  /// - Parameters:
  ///   - request: Request to send to ListScanRuns.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listScanRuns(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_ListScanRunsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_ListScanRunsRequest, Google_Cloud_Websecurityscanner_V1alpha_ListScanRunsResponse> {
    return self.makeUnaryCall(
      path: "/google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListScanRuns",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Stops a ScanRun. The stopped ScanRun is returned.
  ///
  /// - Parameters:
  ///   - request: Request to send to StopScanRun.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func stopScanRun(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_StopScanRunRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_StopScanRunRequest, Google_Cloud_Websecurityscanner_V1alpha_ScanRun> {
    return self.makeUnaryCall(
      path: "/google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/StopScanRun",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// List CrawledUrls under a given ScanRun.
  ///
  /// - Parameters:
  ///   - request: Request to send to ListCrawledUrls.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listCrawledUrls(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_ListCrawledUrlsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_ListCrawledUrlsRequest, Google_Cloud_Websecurityscanner_V1alpha_ListCrawledUrlsResponse> {
    return self.makeUnaryCall(
      path: "/google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListCrawledUrls",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Gets a Finding.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetFinding.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getFinding(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_GetFindingRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_GetFindingRequest, Google_Cloud_Websecurityscanner_V1alpha_Finding> {
    return self.makeUnaryCall(
      path: "/google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/GetFinding",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// List Findings under a given ScanRun.
  ///
  /// - Parameters:
  ///   - request: Request to send to ListFindings.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listFindings(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_ListFindingsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_ListFindingsRequest, Google_Cloud_Websecurityscanner_V1alpha_ListFindingsResponse> {
    return self.makeUnaryCall(
      path: "/google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListFindings",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// List all FindingTypeStats under a given ScanRun.
  ///
  /// - Parameters:
  ///   - request: Request to send to ListFindingTypeStats.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listFindingTypeStats(
    _ request: Google_Cloud_Websecurityscanner_V1alpha_ListFindingTypeStatsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Websecurityscanner_V1alpha_ListFindingTypeStatsRequest, Google_Cloud_Websecurityscanner_V1alpha_ListFindingTypeStatsResponse> {
    return self.makeUnaryCall(
      path: "/google.cloud.websecurityscanner.v1alpha.WebSecurityScanner/ListFindingTypeStats",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

public final class Google_Cloud_Websecurityscanner_V1alpha_WebSecurityScannerClient: Google_Cloud_Websecurityscanner_V1alpha_WebSecurityScannerClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the google.cloud.websecurityscanner.v1alpha.WebSecurityScanner service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Google_Cloud_Websecurityscanner_V1alpha_WebSecurityScannerProvider: CallHandlerProvider {
  /// Creates a new ScanConfig.
  func createScanConfig(request: Google_Cloud_Websecurityscanner_V1alpha_CreateScanConfigRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Websecurityscanner_V1alpha_ScanConfig>
  /// Deletes an existing ScanConfig and its child resources.
  func deleteScanConfig(request: Google_Cloud_Websecurityscanner_V1alpha_DeleteScanConfigRequest, context: StatusOnlyCallContext) -> EventLoopFuture<SwiftProtobuf.Google_Protobuf_Empty>
  /// Gets a ScanConfig.
  func getScanConfig(request: Google_Cloud_Websecurityscanner_V1alpha_GetScanConfigRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Websecurityscanner_V1alpha_ScanConfig>
  /// Lists ScanConfigs under a given project.
  func listScanConfigs(request: Google_Cloud_Websecurityscanner_V1alpha_ListScanConfigsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Websecurityscanner_V1alpha_ListScanConfigsResponse>
  /// Updates a ScanConfig. This method support partial update of a ScanConfig.
  func updateScanConfig(request: Google_Cloud_Websecurityscanner_V1alpha_UpdateScanConfigRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Websecurityscanner_V1alpha_ScanConfig>
  /// Start a ScanRun according to the given ScanConfig.
  func startScanRun(request: Google_Cloud_Websecurityscanner_V1alpha_StartScanRunRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Websecurityscanner_V1alpha_ScanRun>
  /// Gets a ScanRun.
  func getScanRun(request: Google_Cloud_Websecurityscanner_V1alpha_GetScanRunRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Websecurityscanner_V1alpha_ScanRun>
  /// Lists ScanRuns under a given ScanConfig, in descending order of ScanRun
  /// stop time.
  func listScanRuns(request: Google_Cloud_Websecurityscanner_V1alpha_ListScanRunsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Websecurityscanner_V1alpha_ListScanRunsResponse>
  /// Stops a ScanRun. The stopped ScanRun is returned.
  func stopScanRun(request: Google_Cloud_Websecurityscanner_V1alpha_StopScanRunRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Websecurityscanner_V1alpha_ScanRun>
  /// List CrawledUrls under a given ScanRun.
  func listCrawledUrls(request: Google_Cloud_Websecurityscanner_V1alpha_ListCrawledUrlsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Websecurityscanner_V1alpha_ListCrawledUrlsResponse>
  /// Gets a Finding.
  func getFinding(request: Google_Cloud_Websecurityscanner_V1alpha_GetFindingRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Websecurityscanner_V1alpha_Finding>
  /// List Findings under a given ScanRun.
  func listFindings(request: Google_Cloud_Websecurityscanner_V1alpha_ListFindingsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Websecurityscanner_V1alpha_ListFindingsResponse>
  /// List all FindingTypeStats under a given ScanRun.
  func listFindingTypeStats(request: Google_Cloud_Websecurityscanner_V1alpha_ListFindingTypeStatsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Websecurityscanner_V1alpha_ListFindingTypeStatsResponse>
}

extension Google_Cloud_Websecurityscanner_V1alpha_WebSecurityScannerProvider {
  public var serviceName: Substring { return "google.cloud.websecurityscanner.v1alpha.WebSecurityScanner" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: Substring, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "CreateScanConfig":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.createScanConfig(request: request, context: context)
        }
      }

    case "DeleteScanConfig":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.deleteScanConfig(request: request, context: context)
        }
      }

    case "GetScanConfig":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.getScanConfig(request: request, context: context)
        }
      }

    case "ListScanConfigs":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.listScanConfigs(request: request, context: context)
        }
      }

    case "UpdateScanConfig":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.updateScanConfig(request: request, context: context)
        }
      }

    case "StartScanRun":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.startScanRun(request: request, context: context)
        }
      }

    case "GetScanRun":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.getScanRun(request: request, context: context)
        }
      }

    case "ListScanRuns":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.listScanRuns(request: request, context: context)
        }
      }

    case "StopScanRun":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.stopScanRun(request: request, context: context)
        }
      }

    case "ListCrawledUrls":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.listCrawledUrls(request: request, context: context)
        }
      }

    case "GetFinding":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.getFinding(request: request, context: context)
        }
      }

    case "ListFindings":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.listFindings(request: request, context: context)
        }
      }

    case "ListFindingTypeStats":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.listFindingTypeStats(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

